### ISSUE TITLE
Parsing error management

### ISSUE THREAD

**Issue by philn** [gdesmott/gst-log-parser#5]
Currently the parser panicks if it can't parse an entry:
```
thread 'main' panicked at 'invalid hour: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: gst_log_parser::Entry::new
  10: <gst_log_parser::ParserIterator<R> as core::iter::traits::iterator::Iterator>::next
  11: gst_log_diff::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: main
  17: __libc_start_main
  18: _start
```

Maybe `Entry::new()` should return a `Result<Entry,...>` and gracefully handle failures?

**Comment by gdesmott** [comment]
Indeed, I didn't implement proper error management yet. My plan was to do it probably using `failure`.
Patch welcome of course. :)

**Comment by philn** [comment]
I'll have a look :)

**Comment by philn** [comment]
Before writing the parser, did you know about https://docs.rs/nom/5.0.0/nom/ ?
I wonder if a rewrite wouldn't be simpler :) Otherwise I started a patch for the existing code-base, but I think the errors we will emit won't be as accurate as what nom would produce.

**Comment by gdesmott** [comment]
I heard of it, but the initial goal of this project was to learn Rust so I preferred to kept it simple.
I'd rather keep it that way, at least for now, except if we have very good reason to switch.

Your patch looks good, the only missing important bit would be the failing line right?

**Comment by philn** [comment]
There's more `expect` calls to transform as well :) Maybe later today I'll finish the patch.
